/* CHAPTER_QUIZZES.JS — auto-generated by build.py */

var CHAPTER_QUIZ_TOPICS = {
  "polity-ch1": [
    "polity-constitution-making-moderate",
    "polity-constitution-making-moderate-difficult",
    "polity-constitution-making-difficult"
  ],
  "polity-ch2": [
    "polity-fundamental-rights-moderate",
    "polity-fundamental-rights-moderate-difficult",
    "polity-fundamental-rights-difficult"
  ],
  "polity-ch3": [
    "polity-fundamental-duties-moderate",
    "polity-fundamental-duties-moderate-difficult",
    "polity-fundamental-duties-difficult"
  ],
  "polity-ch4": [
    "polity-preamble-moderate",
    "polity-preamble-moderate-difficult",
    "polity-preamble-difficult"
  ],
  "polity-ch5": [
    "polity-union-executive-moderate",
    "polity-union-executive-moderate-difficult",
    "polity-union-executive-difficult"
  ],
  "polity-ch6": [
    "polity-parliament-moderate",
    "polity-parliament-moderate-difficult",
    "polity-parliament-difficult"
  ],
  "polity-ch7": [
    "polity-judiciary-moderate",
    "polity-judiciary-moderate-difficult",
    "polity-judiciary-difficult"
  ],
  "polity-ch8": [
    "polity-state-government-moderate",
    "polity-state-government-moderate-difficult",
    "polity-state-government-difficult"
  ],
  "polity-ch9": [
    "polity-local-self-government-moderate",
    "polity-local-self-government-moderate-difficult",
    "polity-local-self-government-difficult"
  ],
  "polity-ch10": [
    "polity-union-territories-moderate",
    "polity-union-territories-moderate-difficult",
    "polity-union-territories-difficult"
  ],
  "polity-ch11": [
    "polity-emergency-provisions-moderate",
    "polity-emergency-provisions-moderate-difficult",
    "polity-emergency-provisions-difficult"
  ],
  "polity-ch12": [
    "polity-election-commission-moderate",
    "polity-election-commission-moderate-difficult",
    "polity-election-commission-difficult"
  ],
  "polity-ch13": [
    "polity-cag-bodies-moderate",
    "polity-cag-bodies-moderate-difficult",
    "polity-cag-bodies-difficult"
  ],
  "polity-ch14": [
    "polity-dpsp-moderate",
    "polity-dpsp-moderate-difficult",
    "polity-dpsp-difficult"
  ],
  "polity-ch15": [
    "polity-anti-defection-moderate",
    "polity-anti-defection-moderate-difficult",
    "polity-anti-defection-difficult"
  ],
  "polity-ch16": [
    "polity-panchayati-raj-moderate",
    "polity-panchayati-raj-moderate-difficult",
    "polity-panchayati-raj-difficult"
  ],
  "polity-ch17": [
    "polity-amendments-moderate",
    "polity-amendments-moderate-difficult",
    "polity-amendments-difficult"
  ],
  "polity-ch18": [
    "polity-articles-schedules-moderate",
    "polity-articles-schedules-moderate-difficult",
    "polity-articles-schedules-difficult"
  ]
};
