/* EXTRA_CHAPTER_QUIZZES.JS — auto-generated by build_extra.py */

const EXTRA_CHAPTER_QUIZ_TOPICS = {
  "sci-ch101": [
    "sci-ch101-moderate",
    "sci-ch101-moderate-difficult",
    "sci-ch101-difficult"
  ],
  "sci-ch102": [
    "sci-ch102-moderate",
    "sci-ch102-moderate-difficult",
    "sci-ch102-difficult"
  ],
  "sci-ch103": [
    "sci-ch103-moderate",
    "sci-ch103-moderate-difficult",
    "sci-ch103-difficult"
  ],
  "sci-ch104": [
    "sci-ch104-moderate",
    "sci-ch104-moderate-difficult",
    "sci-ch104-difficult"
  ],
  "geo-ch201": [
    "geo-ch201-moderate",
    "geo-ch201-moderate-difficult",
    "geo-ch201-difficult"
  ],
  "geo-ch202": [
    "geo-ch202-moderate",
    "geo-ch202-moderate-difficult",
    "geo-ch202-difficult"
  ],
  "geo-ch203": [
    "geo-ch203-moderate",
    "geo-ch203-moderate-difficult",
    "geo-ch203-difficult"
  ],
  "geo-ch204": [
    "geo-ch204-moderate",
    "geo-ch204-moderate-difficult",
    "geo-ch204-difficult"
  ],
  "eco-ch301": [
    "eco-ch301-moderate",
    "eco-ch301-moderate-difficult",
    "eco-ch301-difficult"
  ],
  "eco-ch302": [
    "eco-ch302-moderate",
    "eco-ch302-moderate-difficult",
    "eco-ch302-difficult"
  ],
  "eco-ch303": [
    "eco-ch303-moderate",
    "eco-ch303-moderate-difficult",
    "eco-ch303-difficult"
  ],
  "eco-ch304": [
    "eco-ch304-moderate",
    "eco-ch304-moderate-difficult",
    "eco-ch304-difficult"
  ],
  "eco-ch305": [
    "eco-ch305-moderate",
    "eco-ch305-moderate-difficult",
    "eco-ch305-difficult"
  ],
  "eco-ch306": [
    "eco-ch306-moderate",
    "eco-ch306-moderate-difficult",
    "eco-ch306-difficult"
  ],
  "ca-ch401": [
    "ca-ch401-moderate",
    "ca-ch401-moderate-difficult",
    "ca-ch401-difficult"
  ],
  "ca-ch402": [
    "ca-ch402-moderate",
    "ca-ch402-moderate-difficult",
    "ca-ch402-difficult"
  ],
  "ca-ch403": [
    "ca-ch403-moderate",
    "ca-ch403-moderate-difficult",
    "ca-ch403-difficult"
  ],
  "ca-ch404": [
    "ca-ch404-moderate",
    "ca-ch404-moderate-difficult",
    "ca-ch404-difficult"
  ],
  "ca-ch405": [
    "ca-ch405-moderate",
    "ca-ch405-moderate-difficult",
    "ca-ch405-difficult"
  ],
  "ca-ch406": [
    "ca-ch406-moderate",
    "ca-ch406-moderate-difficult",
    "ca-ch406-difficult"
  ]
};
