/* HISTORY_CHAPTER_QUIZZES.JS — auto-generated by build_history.py */

var HISTORY_CHAPTER_QUIZ_TOPICS = {
  "history-ch1": [
    "history-prehistoric-moderate",
    "history-prehistoric-moderate-difficult",
    "history-prehistoric-difficult"
  ],
  "history-ch2": [
    "history-ivc-moderate",
    "history-ivc-moderate-difficult",
    "history-ivc-difficult"
  ],
  "history-ch3": [
    "history-vedic-moderate",
    "history-vedic-moderate-difficult",
    "history-vedic-difficult"
  ],
  "history-ch4": [
    "history-buddhism-jainism-moderate",
    "history-buddhism-jainism-moderate-difficult",
    "history-buddhism-jainism-difficult"
  ],
  "history-ch5": [
    "history-mauryan-moderate",
    "history-mauryan-moderate-difficult",
    "history-mauryan-difficult"
  ],
  "history-ch6": [
    "history-post-mauryan-moderate",
    "history-post-mauryan-moderate-difficult",
    "history-post-mauryan-difficult"
  ],
  "history-ch7": [
    "history-gupta-moderate",
    "history-gupta-moderate-difficult",
    "history-gupta-difficult"
  ],
  "history-ch8": [
    "history-post-gupta-moderate",
    "history-post-gupta-moderate-difficult",
    "history-post-gupta-difficult"
  ],
  "history-ch9": [
    "history-delhi-sultanate-moderate",
    "history-delhi-sultanate-moderate-difficult",
    "history-delhi-sultanate-difficult"
  ],
  "history-ch10": [
    "history-mughal-moderate",
    "history-mughal-moderate-difficult",
    "history-mughal-difficult"
  ],
  "history-ch11": [
    "history-maratha-moderate",
    "history-maratha-moderate-difficult",
    "history-maratha-difficult"
  ],
  "history-ch12": [
    "history-vijayanagara-moderate",
    "history-vijayanagara-moderate-difficult",
    "history-vijayanagara-difficult"
  ],
  "history-ch13": [
    "history-bhakti-sufi-moderate",
    "history-bhakti-sufi-moderate-difficult",
    "history-bhakti-sufi-difficult"
  ],
  "history-ch14": [
    "history-advent-europeans-moderate",
    "history-advent-europeans-moderate-difficult",
    "history-advent-europeans-difficult"
  ],
  "history-ch15": [
    "history-british-rule-moderate",
    "history-british-rule-moderate-difficult",
    "history-british-rule-difficult"
  ],
  "history-ch16": [
    "history-revolt-1857-moderate",
    "history-revolt-1857-moderate-difficult",
    "history-revolt-1857-difficult"
  ],
  "history-ch17": [
    "history-freedom-struggle-moderate",
    "history-freedom-struggle-moderate-difficult",
    "history-freedom-struggle-difficult"
  ],
  "history-ch18": [
    "history-social-reformers-moderate",
    "history-social-reformers-moderate-difficult",
    "history-social-reformers-difficult"
  ],
  "history-ch19": [
    "history-partition-independence-moderate",
    "history-partition-independence-moderate-difficult",
    "history-partition-independence-difficult"
  ]
};
